version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        #set up volume to track file changes
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        #set up volume to track file changes
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
    